companies_dict = {
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "GOOGL": "Alphabet Inc.",
    "AMZN": "Amazon.com, Inc.",
    "META": "Meta Platforms, Inc.",
    "NVDA": "NVIDIA Corporation",
    "AMD": "Advanced Micro Devices, Inc.",
    "TSM": "Taiwan Semiconductor Manufacturing Company Limited",
    "INTC": "Intel Corporation",
    "JPM": "JPMorgan Chase & Co.",
    "BAC": "Bank of America Corporation",
    "HDFC.NS": "HDFC Bank Limited",
    "ICICIBANK.NS": "ICICI Bank Limited",
    "TSLA": "Tesla, Inc.",
    "TATAMOTORS.NS": "Tata Motors Limited",
    "MARUTI.NS": "Maruti Suzuki India Limited",
    "JNJ": "Johnson & Johnson",
    "PFE": "Pfizer Inc.",
    "XOM": "Exxon Mobil Corporation",
    "RELIANCE.NS": "Reliance Industries Limited",
}
